"""Remove a coluna data_hora de atendimentos

Revision ID: 1378dd875493
Revises: b05b6d8df3e2
Create Date: 2025-10-07 19:34:53.024629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1378dd875493'
down_revision = 'b05b6d8df3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
