"""Add paciente_id/especialidade_id/criado_por_id to atendimentos

Revision ID: b05b6d8df3e2
Revises: 
Create Date: 2025-09-30 21:37:22.164849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05b6d8df3e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('especialidade_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('criado_por_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pacientes', ['paciente_id'], ['id'])
        batch_op.create_foreign_key(None, 'especialidades', ['especialidade_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['criado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('criado_por_id')
        batch_op.drop_column('especialidade_id')
        batch_op.drop_column('paciente_id')

    # ### end Alembic commands ###
