"""Remove a coluna data_hora de atendimentos

Revision ID: d0e66419bb09
Revises: 1378dd875493
Create Date: 2025-10-09 18:50:57.855640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e66419bb09'
down_revision = '1378dd875493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###
